#! /usr/bin/perl

=head1 NAME

soft-clear - implement clear that does not erase the latest lines on screen

=head1 DESCRIPTION

Calling the 'clear' command with C<C-l> make the more recent lines on
screen to be erased. The new command 'soft-clear', called with C<C-L>
(see the uppercase L) will first add lines to fill the screen and
call the clear command.

=cut

sub on_action {
    my ($self, $action) = @_;

    $action eq "clear"
	and $self->soft_clear;

    ()
}

sub on_init {
    my ($self) = @_;

    my $hotkey = "C-l";

    $self->bind_action ($hotkey, "%:clear")
	or warn "unable to register '$hotkey' as soft clear hotkey\n";

    ()
}

sub soft_clear {
    my ($self) = @_;

    # Do not write when on secondary screen
    if ($self->current_screen == 0) {
	my ($cur_r,$cur_c) = $self->screen_cur;
	my $line = $self->line($cur_r);
	$cur_r -= $line->beg;
	foreach my $i (1..$self->nrow-$cur_r-1) {
	    $self->scr_add_lines("\r\n");
	}
	$self->screen_cur($cur_r, $cur_c);
    }

    ()
}
