#! /usr/bin/perl

=head1 NAME

soft-clear - implement clear that does not erase the latest lines on screen

=head1 DESCRIPTION

Calling the 'clear' command with C<C-l> make the more recent lines on
screen to be erased. The new command 'soft-clear', called with C<C-L>
(see the uppercase L) will first add lines to fill the screen and
call the clear command.

=cut

sub on_action {
    my ($self, $action) = @_;

    $action eq "clear"
	and $self->soft_clear;

    ()
}

sub on_init {
    my ($self) = @_;

    my $hotkey = "C-L";

    $self->bind_action ($hotkey, "%:clear")
	or warn "unable to register '$hotkey' as soft clear hotkey\n";

    ()
}

sub soft_clear {
    my ($self) = @_;

    # Do not write when on secondary screen
    if ($self->current_screen == 0) {
	my $line = $self->line(($self->screen_cur)[0]);
	foreach my $i (1..$self->nrow-1-($line->end-$line->beg)) {
	    $self->scr_add_lines("\r\n");
	}
    }
    $self->key_press (urxvt::ControlMask, 46);

    ()
}
